import { mkdir, writeFile, appendFile, readFile } from 'node:fs/promises';
import { join, dirname } from 'node:path';
import { existsSync } from 'node:fs';
import { createLogger } from '@jonas/shared/utils';

const log = createLogger('vault-writer');

interface NoteFrontmatter {
  title?: string;
  tags?: string[];
  created?: string;
  [key: string]: unknown;
}

export class VaultWriter {
  private vaultPath: string;
  private enabled: boolean;

  constructor(vaultPath = '/data/vault') {
    this.vaultPath = vaultPath;
    this.enabled = process.env.VAULT_SYNC_ENABLED === 'true';
  }

  async initialize(): Promise<void> {
    if (!this.enabled) {
      log.info('Vault writing disabled (VAULT_SYNC_ENABLED not true)');
      return;
    }

    log.info({ vaultPath: this.vaultPath }, 'Initializing vault writer');

    // Create directory structure
    const dirs = ['daily', 'conversations', 'research', 'inbox', 'templates'];

    for (const dir of dirs) {
      await mkdir(join(this.vaultPath, dir), { recursive: true });
    }

    // Create README at root
    const readmePath = join(this.vaultPath, 'README.md');
    if (!existsSync(readmePath)) {
      const readme = `# Jonas Agent Vault

This directory contains notes generated by the Jonas AI agent.

## Structure

- \`daily/\` - Daily notes and summaries
- \`conversations/\` - Conversation exports
- \`research/\` - Research findings and analysis
- \`inbox/\` - Quick captures
- \`templates/\` - Note templates

## Sync

Pull to local Obsidian vault using the sync script:

\`\`\`bash
~/Projects/jonas/scripts/sync-vault.sh
\`\`\`

Or if you've set up the alias:

\`\`\`bash
jvs
\`\`\`

## Integration

These notes are designed to integrate seamlessly with Obsidian:
- YAML frontmatter for metadata
- WikiLinks for cross-references
- Standard markdown formatting
`;

      await writeFile(readmePath, readme, 'utf-8');
      log.info('Created vault README');
    }

    log.info('Vault writer initialized');
  }

  /**
   * Write a note to the vault
   */
  async writeNote(
    relativePath: string,
    content: string,
    frontmatter?: NoteFrontmatter,
  ): Promise<string> {
    if (!this.enabled) {
      throw new Error('Vault writing is disabled');
    }

    const fullPath = join(this.vaultPath, relativePath);

    // Ensure directory exists
    await mkdir(dirname(fullPath), { recursive: true });

    // Build file content
    let fileContent = '';

    // Add frontmatter
    if (frontmatter) {
      fileContent += '---\n';
      for (const [key, value] of Object.entries(frontmatter)) {
        if (Array.isArray(value)) {
          fileContent += `${key}: [${value.map((v) => JSON.stringify(v)).join(', ')}]\n`;
        } else {
          fileContent += `${key}: ${JSON.stringify(value)}\n`;
        }
      }
      fileContent += '---\n\n';
    }

    // Add content
    fileContent += content;

    await writeFile(fullPath, fileContent, 'utf-8');
    log.info({ path: relativePath }, 'Note written');

    return fullPath;
  }

  /**
   * Append content to today's daily note
   */
  async appendToDaily(content: string, section?: string): Promise<string> {
    if (!this.enabled) {
      throw new Error('Vault writing is disabled');
    }

    const today = new Date().toISOString().split('T')[0];
    const dailyPath = join(this.vaultPath, `daily/${today}.md`);

    await mkdir(dirname(dailyPath), { recursive: true });

    // Check if file exists
    const exists = existsSync(dailyPath);

    if (!exists) {
      // Create new daily note with frontmatter
      const frontmatter = {
        title: `Daily Note - ${today}`,
        tags: ['daily'],
        created: new Date().toISOString(),
      };

      let initialContent = '---\n';
      for (const [key, value] of Object.entries(frontmatter)) {
        if (Array.isArray(value)) {
          initialContent += `${key}: [${value.map((v) => JSON.stringify(v)).join(', ')}]\n`;
        } else {
          initialContent += `${key}: ${JSON.stringify(value)}\n`;
        }
      }
      initialContent += '---\n\n';
      initialContent += `# ${today}\n\n`;

      await writeFile(dailyPath, initialContent, 'utf-8');
    }

    // Append entry
    const timestamp = new Date().toLocaleTimeString('en-US', {
      hour: '2-digit',
      minute: '2-digit',
    });

    let entry = '\n';
    if (section) {
      entry += `## ${section}\n\n`;
    } else {
      entry += `## ${timestamp}\n\n`;
    }
    entry += content + '\n';

    await appendFile(dailyPath, entry, 'utf-8');
    log.info({ date: today, section }, 'Appended to daily note');

    return dailyPath;
  }

  /**
   * Create a conversation export
   */
  async exportConversation(
    conversationId: string,
    messages: Array<{ role: string; content: string; timestamp: string }>,
  ): Promise<string> {
    if (!this.enabled) {
      throw new Error('Vault writing is disabled');
    }

    const timestamp = new Date().toISOString().split('T')[0];
    const filename = `${timestamp}-${conversationId.slice(0, 8)}.md`;
    const path = `conversations/${filename}`;

    let content = '';

    for (const msg of messages) {
      const time = new Date(msg.timestamp).toLocaleString();
      content += `### ${msg.role} (${time})\n\n`;
      content += msg.content + '\n\n';
      content += '---\n\n';
    }

    const frontmatter = {
      title: `Conversation ${conversationId.slice(0, 8)}`,
      tags: ['conversation'],
      created: new Date().toISOString(),
      conversationId,
    };

    await this.writeNote(path, content, frontmatter);
    log.info({ conversationId, filename }, 'Conversation exported');

    return path;
  }

  /**
   * Check if vault writing is enabled
   */
  isEnabled(): boolean {
    return this.enabled;
  }
}
